/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;


import code.FacturaProveedor;

/**
 *
 * @author Gianny
 */
public class formRegistrarIngreso extends javax.swing.JFrame {

    FacturaProveedor factproveedor = new FacturaProveedor();
//    C_Proveedor cf = new C_Proveedor();
    
    /**
     * Creates new form formRegistrarIngreso
     */
    public formRegistrarIngreso() {
        initComponents();
        llenarProveedor();
    }
    
    
    private void llenarProveedor(){
//        C_Proveedor fp = new C_Proveedor();
//        ArrayList<Proveedor> listaproveedor = fp.getProveedor();
//        
//        //Limpiar el cbx
//        cbxProveedor.removeAllItems();
//        
//        for (int i = 0; i < listaproveedor.size(); i++) {
//            
//            cbxProveedor.addItem(listaproveedor.get(i).getNombre());
//        }
    }
       
    
    private void agregarIngresoProveedor(){
//        if (txtProducto.getText().equals("") || cbxProveedor.getSelectedItem().equals("") || txtCodigo.getText().equals("") || txtCantidad.getText().equals("") || txtImporte.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "Completar los campos");
//            
//        }else{
//            factproveedor.setCodigo(txtCodigo.getText());
//            factproveedor.setCodigoProveedor(cf.ListarProv(String.valueOf(cbxProveedor.getSelectedItem())).getCodigo());
//            factproveedor.setProducto(txtProducto.getText());
//            factproveedor.setCantidad(Integer.parseInt(txtCantidad.getText()));
//            factproveedor.setImporte(Double.parseDouble(txtImporte.getText()));
//            System.out.println(factproveedor.getProducto());
//            
//                System.out.println(cf.Lista().isEmpty());
//                
//                if (cf.Lista().isEmpty()) {
//                    cf.registrarIngreso(factproveedor);
//                    JOptionPane.showMessageDialog(null, "Registro exitoso");
//                    return;
//                }else{
//                    if (cf.existeIngreso(txtCodigo.getText())) {
//                    
//                    JOptionPane.showMessageDialog(null, "Este Proveedor existente en BD");
//                
//                    }else{
//                        cf.registrarIngreso(factproveedor);
//                    JOptionPane.showMessageDialog(null, "Registro exitoso");
//                }}
//                
//                restartIngreso();
//            
//        }
    }
    
    private void restartIngreso() {
        cbxProveedor.setSelectedItem(null);
        txtCodigo.setText(null);  
        txtCantidad.setText(null);
        txtImporte.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtImporte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 16, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 402, -1));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAgregar.setText("INGRESAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 309, 144, 33));

        txtImporte.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 275, 29));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Importe:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 275, 29));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 267, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Proveedor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        cbxProveedor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 267, 29));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Codigo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        txtProducto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 267, 29));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarIngresoProveedor();
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistrarIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
